old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
            read_write_timeout: 60
            heartbeat: 30
            connection_timeout: 60
            keepalive: false
    producers:
        messaging:
            class: App\Rabbit\MessagingProducer
            connection:       default
            exchange_options: { name: 'qMessages', type: direct }
    consumers:
        messaging:
            connection:       default
            exchange_options: { name: 'qMessages', type: direct }
            queue_options:    { name: 'qMessages'}
            callback:         message_service
            enable_logger:    true

